name: Greeting from Mona

on: 
  workflow_dispatch:
    inputs:
      loglevel:
        description: 'Log Level'
        required: true
        default: 'warning'
      tags:
        description: 'Test'

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: |
          echo "====start===="
          echo ${{ secrets.ACCESS_TOKEN }}
          echo ${{ github.event.inputs.loglevel }}
          echo ${{ github.event.inputs.tags }}
          echo "==== stop ==="
