name: timer
# on:
#   schedule:
#     - cron:  '0 1,12 * * *'
on:
  watch:
    types: [started]
    
jobs:
    update_notion:
        name: get
        runs-on: ubuntu-18.04
        steps:
        - name: print
          run: echo "$PATH"
    
